from pathlib import Path
import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
from typing import Optional

# Initialize FastAPI application
app = FastAPI(
    title="ATM Predictive Maintenance",
    description="Predict ATM failures before they occur",
    version="1.0.0"
)

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Paths
BASE_DIR = Path(__file__).resolve().parent.parent
MODEL_PATH = BASE_DIR / "models" / "atm_failure_model.pkl"
DATA_PATH = BASE_DIR / "data" / "atm_data.csv"
FRONTEND_DIR = BASE_DIR / "frontend"

# Import explanation engine and LangChain analysis
from src.ai_explainer import generate_explanation
from src.langchain_analyzer import generate_analysis

# Load ML Model
model = None
if MODEL_PATH.exists():
    model = joblib.load(MODEL_PATH)
else:
    print(f"Warning: Model file not found at {MODEL_PATH}")

# Load Dataset from data/atm_data.csv
atm_df = None
if DATA_PATH.exists():
    atm_df = pd.read_csv(DATA_PATH)
    print(f"Loaded {len(atm_df)} records from {DATA_PATH}")
else:
    print(f"Warning: Data file not found at {DATA_PATH}")


class SensorInput(BaseModel):
    atm_id: str = Field(default="ATM1", description="ATM identifier")
    temperature: float = Field(..., ge=0, le=150, description="Temperature", example=90.0)
    network_errors: int = Field(..., ge=0, le=500, description="Network Errors", example=20)
    dispenser_errors: int = Field(..., ge=0, le=200, description="Dispenser Errors", example=10)
    cpu_usage: float = Field(..., ge=0, le=100, description="CPU Usage (%)", example=92.0)
    transaction_failures: int = Field(..., ge=0, le=500, description="Transaction Failures", example=15)


@app.get("/api/health")
def health_check():
    """Returns the health status of the API, dataset, and model availability."""
    return {
        "status": "healthy",
        "model_loaded": model is not None,
        "data_loaded": atm_df is not None,
        "total_records": len(atm_df) if atm_df is not None else 0
    }


@app.get("/api/atms")
def get_atms(limit: int = 1000, search: Optional[str] = None):
    """
    Returns data from data/atm_data.csv generated by the ML model data generator.
    Includes failure_status counts and full records for selection.
    """
    if atm_df is None:
        raise HTTPException(status_code=500, detail="atm_data.csv is not loaded.")

    df = atm_df
    if search:
        df = df[df["atm_id"].str.contains(search, case=False, na=False)]

    records = df.head(limit).to_dict(orient="records")

    total_records = len(atm_df)
    failure_count = int((atm_df["failure_status"] == 1).sum())
    normal_count = int((atm_df["failure_status"] == 0).sum())

    return {
        "total_atms": total_records,
        "failure_count": failure_count,
        "normal_count": normal_count,
        "atms": records
    }


@app.get("/api/atms/{atm_id}")
def get_atm_by_id(atm_id: str):
    """
    Looks up an ATM by ID from data/atm_data.csv and runs live prediction.
    """
    if atm_df is None:
        raise HTTPException(status_code=500, detail="atm_data.csv is not loaded.")

    clean_id = atm_id.strip()
    if clean_id.isdigit():
        normalized_id = f"ATM{clean_id}"
    else:
        normalized_id = clean_id.upper()

    matches = atm_df[atm_df["atm_id"].str.upper() == normalized_id]
    if matches.empty:
        raise HTTPException(status_code=404, detail=f"ATM {atm_id} not found in data/atm_data.csv.")

    row = matches.iloc[0].to_dict()

    sensor_input = SensorInput(
        atm_id=str(row["atm_id"]),
        temperature=float(row["temperature"]),
        network_errors=int(row["network_errors"]),
        dispenser_errors=int(row["dispenser_errors"]),
        cpu_usage=float(row["cpu_usage"]),
        transaction_failures=int(row["transaction_failures"])
    )

    return predict_failure(sensor_input)


@app.post("/api/predict")
def predict_failure(data: SensorInput):
    """
    Runs model prediction and generates explanation using exact backend logic.
    Used for both existing ATM evaluation and dry running new ATM values.
    """
    if model is None:
        raise HTTPException(status_code=500, detail="ML model is not loaded.")

    sample = pd.DataFrame([
        {
            "temperature": data.temperature,
            "network_errors": data.network_errors,
            "dispenser_errors": data.dispenser_errors,
            "cpu_usage": data.cpu_usage,
            "transaction_failures": data.transaction_failures
        }
    ])

    try:
        prediction_val = int(model.predict(sample)[0])
        
        failure_prob = None
        if hasattr(model, "predict_proba"):
            probs = model.predict_proba(sample)[0]
            if len(probs) > 1:
                failure_prob = round(float(probs[1]) * 100, 1)
            else:
                failure_prob = round(float(probs[0]) * 100, 1)
        else:
            failure_prob = 100.0 if prediction_val == 1 else 0.0

        # Exact backend explanation
        explanation = generate_explanation(
            data.temperature,
            data.network_errors,
            data.dispenser_errors,
            data.transaction_failures,
            prediction_val
        )

        langchain_analysis = generate_analysis(
            data.temperature,
            data.cpu_usage,
            data.network_errors,
            data.dispenser_errors,
            data.transaction_failures,
            explanation["risk_level"]
        )

        # Status banner from app.py
        if explanation["risk_level"] == "HIGH RISK":
            status_banner = "⚠️ High Risk: ATM Failure Likely"
        elif explanation["risk_level"] == "MEDIUM RISK":
            status_banner = "⚠️ Medium Risk: ATM Requires Attention"
        else:
            status_banner = "✅ ATM Operating Normally"

        return {
            "atm_id": data.atm_id,
            "prediction": prediction_val,
            "failure_status": prediction_val,
            "failure_probability": failure_prob,
            "risk_level": explanation["risk_level"],
            "reasons": explanation["reasons"],
            "recommendation": explanation["recommendation"],
            "langchain_analysis": langchain_analysis,
            "status_banner": status_banner,
            "telemetry": {
                "temperature": data.temperature,
                "network_errors": data.network_errors,
                "dispenser_errors": data.dispenser_errors,
                "cpu_usage": data.cpu_usage,
                "transaction_failures": data.transaction_failures
            }
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Inference error: {str(e)}")


# Serve static frontend files
if FRONTEND_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(FRONTEND_DIR)), name="static")

    @app.get("/")
    def serve_ui():
        index_file = FRONTEND_DIR / "index.html"
        if index_file.exists():
            return FileResponse(str(index_file))
        return {"message": "index.html not found"}
